stages:
  - test
  - build
  - publish

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

test:
  stage: test
  image: openjdk:8-jdk
  script:
    - chmod +x gradlew
    - ./gradlew test
    - ./gradlew dependencyCheckAnalyze
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
    paths:
      - build/reports/
    expire_in: 1 week

build:
  stage: build
  image: openjdk:8-jdk
  script:
    - chmod +x gradlew
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/
    expire_in: 1 week
  only:
    - main
    - develop

publish:
  stage: publish
  image: openjdk:8-jdk
  script:
    - chmod +x gradlew
    - ./gradlew publish
  only:
    - main
  when: manual 